README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.22.0**!

fix(version): windows_exporter updated to `0.22.0` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.23.1**!

fix(version): windows_exporter updated to `0.23.1` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.24.0**!

fix(version): windows_exporter updated to `0.24.0` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.25.0**!

fix(version): windows_exporter updated to `0.25.0` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.25.1**!

fix(version): windows_exporter updated to `0.25.1` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.26.0**!

fix(version): windows_exporter updated to `0.26.0` release

---

README.md
defaults/main.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.26.2**!

fix(version): windows_exporter updated to `0.26.2` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.27.0**!

fix(version): windows_exporter updated to `0.27.0` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.27.2**!

fix(version): windows_exporter updated to `0.27.2` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.29.0**!

fix(version): windows_exporter updated to `0.29.0` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.29.1**!

fix(version): windows_exporter updated to `0.29.1` release

---

tasks/install.yml

* When antmelekhin.windows_exporter role is being called as a sub-role and the "download windows exporter" task is inheriting become: true this task might fail to ansible process not being able to become sudo on localhost.
* In prometheus ansible collection other exporters like node_exporter also explicitly set become to false in tasks that have delegate_to: localhost
* Runs fine with become_fase as this does not need elevated privileges

fix: never use sudo for downloading windows_exporter

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.29.2**!

fix(version): windows_exporter updated to `0.29.2` release

---

vars/main.yml

* Not on all Windows versions the "-bit" substring in ansible_architecture is spelled in lowercase. On some Windows versions ansible_architecture contains "-Bit" spelled with a capital B which results in the mapping not matching and therefore a failing download of windows_exporter.
* This commit fixes deployment on some Windows versions like e.g. Windows 10 (tested)

fix: normalize ansible_architecture before mapping it in __windows_exporter_architecture evaluation

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.0**!

fix(version): windows_exporter updated to `0.30.0` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.1**!

fix(version): windows_exporter updated to `0.30.1` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.2**!

fix(version): windows_exporter updated to `0.30.2` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.4**!

fix(version): windows_exporter updated to `0.30.4` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.5**!

fix(version): windows_exporter updated to `0.30.5` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.6**!

fix(version): windows_exporter updated to `0.30.6` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.30.7**!

fix(version): windows_exporter updated to `0.30.7` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.31.2**!

fix(version): windows_exporter updated to `0.31.2` release

---

defaults/main.yml
meta/argument_specs.yml

The upstream [windows_exporter](https://github.com/prometheus-community/windows_exporter/releases) released new software version - **0.31.3**!

fix(version): windows_exporter updated to `0.31.3` release
